DATA SEGMENT
    STAT1 EQU 00100100B
    STAT2 EQU 01000100B 
    STAT3 EQU 10000001B
    STAT4 EQU 10000010B 
    T0 EQU 280H
    T1 EQU 281H
    T2 EQU 282H
    CTL53 EQU 283H
    PA EQU 288H
    PB EQU 289H
    PC EQU 28AH
    CTL55 EQU 28BH
    TAB DB 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH
           77H,7CH,39H,5EH,79H,71H,73H,3EH,6EH,80H
           00H
    TIME DB 30H
DATA ENDS

CODE SEGMENT
    ASSUEM CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX

    MOV DX,CTL53
    MOV AL,00100111B
    OUT DX,AL
    MOV DX,T0
    MOV AL,10H
    OUT DX,AL

    MOV DX,CTL53
    MOV AL,01100111B
    OUT DX,AL
    MOV DX,T1
    MOV AL,10H
    OUT DX,AL

    MOV DX,CTL55
    MOV AL,10001000B
    OUT DX,AL
AG:
    MOV DX,PB
    MOV AL,STAT1
    OUT DX,AL
AG1:
    CALL DSP

    MOV AL,TIME
    SUB AL,1
    DAS
    MOV TIME,AL
    CALL CRT
    CMP AL,00000011B
    JNZ AG
    MOV DX,PB
    MOV AL,STAT2
    OUT DX,AL
AG2:
    CALL DSP

    MOV AL,TIME
    SUB AL,1
    DAS
    MOV TIME,AL
    CALL CRT
    CMP AL,00000000B
    JNZ AG2
    MOV TIME,30H
    MOV DX,PB
    MOV AL,STAT3
    OUT DX,AL
AG3:
    CALL DSP

    MOV AL,TIME 
    SUB AL,1
    DAS
    MOV TIME,AL
    CALL CRT
    CMP AL,00000011B
    JNZ AG3
    MOV DX,PB
    MOV AL,STAT4
    OUT DX,AL
AG4:
    CALL DSP
    MOV AL,TIME
    SUB AL,1
    DAS
    MOV TIME,AL
    CALL CRT
    CMP AL,00000000B
    JNZ AG4
    MOV TIME,30H
    JMP AG

    MOV AH,4CH
    INT 21H
;-----
DSP PROC
    PUSH DX
    PUSH AX
L:
    CALL LED_8
    MOV DX,PC
    IN  AL,DX
    TEST AL,10000000B
    JNZ L 
L1:
    CALL LED_8
    MOV DX,PC
    IN  AL,DX
    TEST AL,10000000B
    JZ LA

    POP DX
    POP AX
DSP ENDP
;-----
LED_8
    PUSH DX
    PUSH AX

    MOV BX,OFFSET TAB
    MOV CL,4
    MOV AL,TIME
    ROL AL,CL
    AND AL,0FH
    XLAT
    MOV DX,PA
    OUT DX,AL
    MOV DX,PC
    MOV AL,00000010B
    OUT DX,AL
    MOV DX,PC
    MOV AL,0
    OUT DX,AL
    MOV AL,TIME
    AND AL,0FH
    XLAT
    MOV DX,PA
    OUT DX,AL
    MOV DX,PC
    MOV AL,00000010B
    OUT DX,AL
    MOV DX,PC
    MOV AL,0
    OUT DX,AL

    POP AX
    POP DX
    RET
LED_8 ENDP
;-----
CRT PROC NEAR
    PUSH DX
    PUSH AX

    MOV CH,2
    MOV CL,4
    MOV AL,TIME
C:
    ROR AL,CL
    MOV DL,AL
    AND DL,0FH
    CMP DL,9
    JBE NEX
    ADD DL,7
NEX:
    ADD DL,30H
    MOV AH,02H
    INT 21H 
    DEC CH
    JNZ C
    MOV DL,20H 
    MOV AH,02H 
    INT 21H 

    POP AX
    POP DX
    RET
CRT ENDP
CODE ENDS
END START