;延时法，16次产生三角波，最高点-2.5v
DATE SEGMENT
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK1
START:
    MOV AX,DATA
    MOV DS,AX
    
    MOV AL,00H
DRAW_ASCEND_LINE:
    MOV DX,280H
    OUT DX,AL
    CALL DELAY
    CMP AL,80H
    JZ DRAW_DESCEND_LINE
    ADD AL,08H
    JMP DRAW_ASCEND_LINE
DRAW_DESCEND_LINE:
    SUB AL,08H
    MOV DX,280H
    OUT DX,AL
    CALL DELAY
    CMP AL,00H
    JZ DRAW_ASCEND_LINE
    JMP DRAW_DESCEND_LINE
    MOV AH,4CH
    INT 21H
;-----
DELAY PROC NEAR
    PUSH CX
    MOV CX,200H
L1:
    LOOP L1
    
    POP CX
    RET
DELAY ENDP
CODE ENDS
END START